package constants

import global_constants "github.com/OntoLedgy/ol_common_services/code/constants"

const UUID_COLUMN_NAME_SEPARATOR = "_"

const UUIDIFIED_DATAFRAME_PREFIX = "uuidified"
const UUIDIFIED_DATAFRAME_DATAFRAME_NAME = UUIDIFIED_DATAFRAME_PREFIX + UUID_COLUMN_NAME_SEPARATOR + "tables"
const UUIDIFIED_COLUMN_DATAFRAME_NAME = UUIDIFIED_DATAFRAME_PREFIX + UUID_COLUMN_NAME_SEPARATOR + "columns"
const UUIDIFIED_CELL_DATAFRAME_NAME = UUIDIFIED_DATAFRAME_PREFIX + UUID_COLUMN_NAME_SEPARATOR + "cells"

const UUIDIFIED_OBJECT_NAME_COLUMN_NAME = "names"
const UUIDIFIED_COLUMN_PARENT_COLUMN_NAME = "table_uuids"
const UUIDIFIED_CELL_COLUMN_PARENT_COLUMN_NAME = "column_uuids"
const UUIDIFIED_CELL_ROW_PARENT_COLUMN_NAME = "row_uuids"
const UUIDIFIED_OBJECT_TYPE_COLUMN_NAME = "type_uuids"
const LAST_USED_COLUMN_NAME = "last_used_in_run"

const TEMPORARY_UUIDS_COLUMN_NAME = "temporary" + UUID_COLUMN_NAME_SEPARATOR + global_constants.UUIDS_COLUMN_NAME
const RUN_UUIDS_COLUMN_NAME = "run" + UUID_COLUMN_NAME_SEPARATOR + global_constants.UUIDS_COLUMN_NAME
const TEMPORARY_RUN_UUIDS_COLUMN_NAME = "temporary" + UUID_COLUMN_NAME_SEPARATOR + RUN_UUIDS_COLUMN_NAME
